### PR TITLE
Simplify impl. of GCR plugin and make 0.5 ready

### PR DESCRIPTION
**Pull request by benschumacher**

### CODE REVIEW

**Comment by bradrydzewski** [comment]
@benschumacher awesome ... quick question ... what are your thoughts on adding this to the drone-docker repository and building both `plugins/docker` and `plugins/gcr` at the same time? That way it is always up to date with the latest features?

**Comment by benschumacher** [comment]
Makes a ton of sense to me. Seems like the same could be done with the ECR version. Do you want me to make a PR for those?

**Comment by bradrydzewski** [comment]
Yes, that would be awesome (sorry for delay). Thanks!

**Comment by tonglil** [comment]
I'd love to see this in plugins/docker.

**Comment by schugh** [comment]
I have a port up on https://github.com/stayfari/drone-gcr that I've been using for just under 2 months.  I had responded to an issue posting about its existence a few months back.

**Comment by stephansnyt** [comment]
@benschumacher hey, I hope you don't mind but I didn't want to wait for this, I submitted a PR based on your work to `drone-docker`

https://github.com/drone-plugins/drone-docker/pull/129

**Comment by bradrydzewski** [comment]
the plugin was moved and now uses plugins/docker as a base with a simple wrapper
https://github.com/drone-plugins/drone-docker/tree/master/cmd/drone-docker-gcr

**Pull request closed without merging**
