### PR TITLE
Add dry run option

### PR DESCRIPTION
**Pull request by tonglil**
Add option to not push images to registry (like `drone-docker` https://github.com/drone-plugins/drone-docker).

Also adds the documentation from the stale PR.

### CODE REVIEW

**Comment by tboerger** [comment]
@bradrydzewski what do you think? Do you want to update the 0.4 release or is it frozen?

**Comment by tonglil** [comment]
I think makes sense to get non-BC updates into 0.4 since 0.5 is still pre-release.

**Comment by tboerger** [comment]
But it's still a feature and I don't know if brad wants to accept new features

**Comment by tonglil** [comment]
Ok thanks.

It would be great if I can know if it is the case or not and split out the doc changes. Colleagues have been referring to the docs and the missing options are not great.

**Comment by bradrydzewski** [comment]
plugin now uses plugins/docker as a base with a simple wrapper, so it now supports dry run
https://github.com/drone-plugins/drone-docker/tree/master/cmd/drone-docker-gcr

**Pull request closed without merging**
