### PR TITLE
Add an option to allow caching docker local files

### PR DESCRIPTION
**Pull request by yunzhu-li**
This adds cache_directory option which sets the graph directory of
docker daemon, allowing users to carry cached layers to future builds.

Using with https://github.com/drone-plugins/drone-cache, it can provide
significant speed up for future long builds.

### CODE REVIEW

**Comment by tboerger** [comment]
I would prefer the same behavior like drone-docker

**Comment by yunzhu-li** [comment]
Do you mean the behavior in release version (http://readme.drone.io/plugins/docker/) or `master` as they seem very different?

**Comment by tboerger** [comment]
Like the master branch of drone-docker

**Comment by yunzhu-li** [comment]
Looks like they behave completely different in passing data, how are the values `daemon.*` defined? I couldn't find anywhere or an example `.yml` file. I'm not going to refactor this plugin at this time but would be happy to make the `.yml` config field same for easier update in the future.

**Pull request closed without merging**
