### PR TITLE
Push version update to Docker Hub

### PR DESCRIPTION
**Pull request by yunzhu-li**
See https://github.com/drone-plugins/drone-gcr/pull/15

### CODE REVIEW

**Comment by tboerger** [comment]
LGTM

**Comment by tboerger** [comment]
@bradrydzewski so it doesn't publish anymore because the required secrets are not set anymore?

**Comment by yunzhu-li** [comment]
@tboerger @bradrydzewski Could you try to build / publish it? It's still not updated and we are getting closer to deprecation date. Thanks!

**Comment by tboerger** [comment]
It's out of my control, that's up to @bradrydzewski

**Comment by yunzhu-li** [comment]
@bradrydzewski Could you please try building and publishing the plugin to Docker Hub? Since the deprecation should be on Feb 15th (2 days from now!) it is important that this to be pushed to Docker Hub, otherwise some of the systems in production would be affected. We use Drone 0.4, this plugin is privileged and it seems not trivial to run our own fork on every repo. Thanks!

**Comment by bradrydzewski** [comment]
@yunzhu-li done

**Comment by yunzhu-li** [comment]
Thanks!

**Pull request merged**
